services:
  web:
    build: .
    image: 'brecheisen/mosamatic-web-intel:${VERSION:-latest}'
    platform: linux/amd64
    environment:
      - DATA_DIR=/data
      - VERSION=${VERSION:-latest}
      - POSTGRES_DB=${POSTGRES_DB:-postgres}
      - POSTGRES_USER=${POSTGRES_USER:-root}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-foobar}
      - POSTGRES_HOST=${POSTGRES_HOST:-postgresql-database-hofl8yo7dj78edsxy3hsaze4}
      - POSTGRES_PORT=${POSTGRES_PORT:-5432}
      - DOCKER=1
      - ADMIN_USER=${ADMIN_USER:-admin}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-admin}
      - SECRET_KEY=${SECRET_KEY:-f9sd7f97sdf89as7fd98as7d9f7sad9f}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-*}
    ports:
      - '8100:8001'
    volumes:
      - 'mosamatic_data:/data'
      - './pipelines:/pipelines'

volumes:
  mosamatic_data: null

networks:
  default:
    name: mosamatic_network
